/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Control.ControlLenguaje;
import Control.ControlPelicula;
import Modelo.Leguaje;
import Modelo.Peliculas;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author jose_dav.gomez
 */
public class ModificarPe extends javax.swing.JFrame {

    boolean encontrado;
    Peliculas peliEncontrada;
    LinkedList<Leguaje> ListaLenguajes;
    Principal GUIPrincipal;
    boolean continuar;

    /**
     * Creates new form ModificarPe
     */
    public ModificarPe() {
        initComponents();

        this.setLocationRelativeTo(this);

        ListaLenguajes = new LinkedList<>();
        traerLenguajes();

        encontrado = false;
        continuar = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LastUpdate = new com.toedter.calendar.JDateChooser();
        Rating = new javax.swing.JComboBox();
        Caracteristica = new javax.swing.JComboBox();
        Lenguaje = new javax.swing.JComboBox();
        LenguajeOriginal = new javax.swing.JComboBox();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Modificar Pelicula");

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Pelicula");

        jLabel2.setText("Title *");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel3.setText("Language *");

        jLabel4.setText("Description");

        jLabel5.setText("Rental duration *");

        jLabel6.setText("Replacement cost *");

        jLabel7.setText("Last update");

        jLabel8.setText("Original language");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("Release year");

        jLabel10.setText("Rental rate *");

        jLabel11.setText("Length");

        jLabel12.setText("Rating");

        jLabel13.setText("Special features");

        LastUpdate.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        LastUpdate.setMinSelectableDate(new java.util.Date(-62135747892000L));

        Rating.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------", "G", "PG", "PG-13", "R", "NC-17" }));

        Caracteristica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------", "Trailers", "Commentaries", "Deleted Scenes", "Behind the Scenes" }));

        Lenguaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------" }));

        LenguajeOriginal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------" }));

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel14.setText("New Last update *");

        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jTextField10)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(Caracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 15, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField12))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LenguajeOriginal, 0, 107, Short.MAX_VALUE)
                                            .addComponent(Lenguaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(LastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel6))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LenguajeOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(Rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Caracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int idFilm = -1;

        try {
            idFilm = Integer.parseInt(jTextField1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla ID pelicula.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (idFilm != -1) {

            ControlPelicula CP = new ControlPelicula();

            peliEncontrada = CP.BuscarPelicula(idFilm);

            if (peliEncontrada != null) {
                encontrado = true;

                jTextField2.setText(peliEncontrada.getTitle());

                if (peliEncontrada.getDescription() != "null") {
                    jTextArea1.setText(peliEncontrada.getDescription());
                } else {
                    jTextArea1.setText("");
                }

                if (peliEncontrada.getRelease_year() != 0) {
                    jTextField9.setText(String.valueOf(peliEncontrada.getRelease_year()));
                } else {
                    jTextField9.setText("");
                }

                jTextField5.setText(String.valueOf(peliEncontrada.getRental_duration()));
                jTextField10.setText(String.valueOf(peliEncontrada.getRental_rate()));
                jTextField12.setText((peliEncontrada.getLast_update()));

                if (peliEncontrada.getLength() != 0) {
                    jTextField11.setText(String.valueOf(peliEncontrada.getLength()));
                } else {
                    jTextField11.setText("");
                }

                jTextField6.setText(String.valueOf(peliEncontrada.getReplacement_cost()));

                LenguajeFilm(peliEncontrada.getLanguage_id());
                LenguajeOriginalFilm(peliEncontrada.getOriginal_language_id());

                if (peliEncontrada.getRating() != "null") {
                    Rating.setSelectedItem(peliEncontrada.getRating());
                } else {
                    Rating.setSelectedIndex(0);
                }

                if (peliEncontrada.getSpecial_features() != "null") {
                    Caracteristica.setSelectedItem(peliEncontrada.getSpecial_features());
                } else {
                    Caracteristica.setSelectedIndex(0);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No se encontó la pelicula en la base de datos.");
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int idFilm = Integer.parseInt(jTextField1.getText());
        String title = jTextField2.getText();
        String description = jTextArea1.getText();
        int language_id = PKLenguaje(Lenguaje.getSelectedItem().toString());
        int original_language_id = PKLenguaje(LenguajeOriginal.getSelectedItem().toString());
        String rating = Rating.getSelectedItem().toString();
        String special_features = Caracteristica.getSelectedItem().toString();

        LastUpdate.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = LastUpdate.getDate();
        String last_update = peliEncontrada.getLast_update();
        
        if (date != null) {
            last_update = df.format(date);
            System.out.println(last_update);
        }

        if (Lenguaje.equals("---------------")) {
            JOptionPane.showMessageDialog(null, "Ingrese un lenguaje vàlido.", "Error", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        if (LenguajeOriginal.equals("---------------")) {
            language_id = -1;
        }

        int rental_duration = -1;
        double rental_rate = -1;
        int length = -1;
        double replacement_cost = -1;
        int release_year = -1;

        try {
            rental_duration = Integer.parseInt(jTextField5.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla rental duration.", "Error", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        try {
            rental_rate = Double.parseDouble(jTextField10.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla rental rate.", "Error", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        if (!jTextField11.getText().equals("")) {
            try {
                length = Integer.parseInt(jTextField11.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla duracion.", "Error", JOptionPane.ERROR_MESSAGE);
                continuar = false;
            }
        }

        try {
            replacement_cost = Double.parseDouble(jTextField6.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla Replacement cost .", "Error", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        if (!jTextField9.getText().equals("")) {
            try {
                release_year = Integer.parseInt(jTextField9.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numerico en la casilla Release year.", "Error", JOptionPane.ERROR_MESSAGE);
                continuar = false;
            }
        }

        if (title.equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un titulo para la película.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        //Variable rental_duration
        if (jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba una duracion de renta para la película.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        //Variable rental_rate
        if (jTextField10.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba una calificacion de renta para la película.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        //variable Replacement cost 
        if (jTextField6.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba un costo para la película.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            continuar = false;
        }

        if (continuar) {
            Peliculas peli = new Peliculas(title, description, release_year, language_id, original_language_id, rental_duration, rental_rate, length, replacement_cost, rating, special_features, last_update);
            ControlPelicula CP = new ControlPelicula();
            boolean t = CP.modificarPelicula(peli, idFilm);

            if (t) {

                JOptionPane.showMessageDialog(null, "Datos actualizados.");

            } else {

                JOptionPane.showMessageDialog(null, "Datos no actualizados.");

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GUIPrincipal = new Principal();
        GUIPrincipal.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPe().setVisible(true);
            }
        });
    }

    public int PKLenguaje(String leng) {

        int pkLeng = -1;

        for (int i = 0; i < ListaLenguajes.size(); i++) {

            if (ListaLenguajes.get(i).getName() == leng) {

                pkLeng = ListaLenguajes.get(i).getIdLenguaje();

            }

        }
        return pkLeng;
    }

    public void LenguajeFilm(int LenguajeID) {

        for (int i = 0; i < ListaLenguajes.size(); i++) {

            if (ListaLenguajes.get(i).getIdLenguaje() == LenguajeID) {

                Lenguaje.setSelectedItem(ListaLenguajes.get(i).getName());
            }

        }

    }

    public void LenguajeOriginalFilm(int LenguajeID) {

        for (int i = 0; i < ListaLenguajes.size(); i++) {

            if (ListaLenguajes.get(i).getIdLenguaje() == LenguajeID) {

                LenguajeOriginal.setSelectedItem(ListaLenguajes.get(i).getName());
            }

        }

    }

    private void traerLenguajes() {
        //Se trae todas las categorías pertenecientes a la BD
        ControlLenguaje CC2 = new ControlLenguaje();

        ListaLenguajes = CC2.LeerLenguaje();

        for (int i = 0; i < ListaLenguajes.size(); i++) {

            Lenguaje.addItem(ListaLenguajes.get(i).getName());
            LenguajeOriginal.addItem(ListaLenguajes.get(i).getName());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Caracteristica;
    private com.toedter.calendar.JDateChooser LastUpdate;
    private javax.swing.JComboBox Lenguaje;
    private javax.swing.JComboBox LenguajeOriginal;
    private javax.swing.JComboBox Rating;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
